[platformio]
default_envs = esp32-s3

[env]
platform = espressif32@6.9.0
framework = arduino
lib_deps = bblanchon/ArduinoJson@6.21.5
monitor_speed = 115200
board_build.partitions = huge_app.csv

[env:esp32]
board = esp32dev

[env:esp32-s3]
board = esp32-s3-devkitc-1
upload_speed = 115200
board_upload.flash_size = 8MB
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
